### ISSUE TITLE
关于服务器功能的建议

### ISSUE THREAD

**Issue by OcrSu** [lemon-slice-studio/Barter#1]
可以添加“无限交易”这样一个功能嘛
我想在主城设置一个无限交易的交易所，玩家们所付出的物品不需要存储
这样可以实现无人化管理商业街

因为某些问题村民失去了防御标签，我无法让其无敌，所以才来寻求模组的帮助
这里是纯forge服务器
谢谢！

**Comment by RoShioLeo** [comment]
嗯，在考虑计划内

**Comment by OcrSu** [comment]
要不不考虑了233

**Comment by RoShioLeo** [comment]
很抱歉已经没有精力开发和维护模组了

**Comment by OcrSu** [comment]
表示理解。
